//L.165 : we want to make like a tokens so can't view any page without it so we make the reducer here because we want to set the tokens to a redux
// the token is auto generated by Google sin in and we can git it by user or action . uid
// if we have a state so you are authenticated else not

export default (state = {}, action) => {
  switch (action.type) {
    case "LOGIN":
      return {
        uid: action.uid,
      };
    case "LOGOUT":
      return {};
    default:
      return state;
  }
};
